[package]
name = "roxanne"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.12", features = ["advanced"] }

[patch.crates-io]
iced_widget = { path = "vendor/iced_widget" }

[dev-dependencies]
criterion = "0.5"
tempfile = "3.12"

[[bench]]
name = "text_buffer"
harness = false
